# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100)),
                ('sna', models.CharField(max_length=100)),
                ('tot', models.IntegerField()),
                ('sbi', models.IntegerField()),
                ('sarea', models.CharField(max_length=100)),
                ('mday', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('ar', models.CharField(max_length=100)),
                ('sareaen', models.CharField(max_length=100)),
                ('aren', models.CharField(max_length=100)),
                ('bemp', models.IntegerField()),
                ('act', models.BooleanField(default=True)),
            ],
        ),
    ]
