# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='ar',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='sarea',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='sna',
            field=models.TextField(max_length=100),
        ),
    ]
