# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubike', '0002_auto_20160212_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='sarea',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='sna',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='station',
            name='sno',
            field=models.IntegerField(max_length=100),
        ),
    ]
